version: "3.5"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin@123
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    # ports:
    #   - target: 5043
    #     published: 5043
    #     protocol: tcp
    #     mode: host
    #   - target: 9600
    #     published: 9600
    #     protocol: tcp
    #     mode: host
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.3.2
    depends_on:
      - logstash
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/home/logs/
